######################################################################
Django Facebook HOWTO
######################################################################

Last updated June 12th 2012, by Adam Ever-Hadani <adamhadani@gmail.com>

Facebook Permissions
--------------------
To specify custom set of facebook permissions to ask for, use the FACEBOOK_DEFAULT_SCOPE setting, e.g in your settings.py:

FACEBOOK_DEFAULT_SCOPE = ['email', 'user_events', 'user_likes', 'user_interests', 'read_stream']

