######################################################################
Django Facebook HOWTO
######################################################################

Last updated June 12th 2012, by Adam Ever-Hadani <adamhadani@gmail.com>

.. contents:: Table of Contents

Tips & Tricks
--------------
* **Facebook Permissions** - To specify custom set of facebook permissions to ask for, use the FACEBOOK_DEFAULT_SCOPE setting, e.g in your settings.py:

    FACEBOOK_DEFAULT_SCOPE = ['email', 'user_events', 'user_likes', 'user_interests', 'read_stream']

  For full reference of available permission strings, See `Here <https://developers.facebook.com/docs/authentication/permissions/>`_.

Troubleshooting
---------------
* OSError after facebook connect dialog  (e.g Permission denied: '/Library/WebServer/images')
    This happens when the framework attempts to save the  users' profile image locally and MEDIA_ROOT is not configured properly in your settings file.
    Make sure MEDIA_ROOT points to a valid existing directory and that it is **R/W-able by the webserver context/user**
* TemplateDoesNotExist at /accounts/logout/
    This happens when you try to sign out a user by hitting the /accounts/logout/ url without a ?next=<redirect_url> query parameter.
    By default, Django-facebook expects you to have a template for this at registration/logout.html as the landing page following a logout.
    Either create this (e.g under your /templates subdir) or supply the ?next= parameter (e.g /accounts/logout/?next=/).
    NOTE: The default redirect URLs correspond to the ones used by the django-registration app. There are various default templates
    floating around the interwebs for this, c.f `This <https://github.com/yourcelf/django-registration-defaults>`_


